/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumListsView: typeof import('./components/AlbumListsView.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    EpisodeListsView: typeof import('./components/EpisodeListsView.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    PlaylistsView: typeof import('./components/PlaylistsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaledImage: typeof import('./components/ScaledImage.vue')['default']
    ShowListsView: typeof import('./components/ShowListsView.vue')['default']
    TrackListsView: typeof import('./components/TrackListsView.vue')['default']
    VolumeControl: typeof import('./components/VolumeControl.vue')['default']
  }
}
