name: pistereo2

services:
  pistereo2-media:
    image: guidcruncher/pistereo2:latest
    extra_hosts:
      - pistereo2:127.0.0.1
    dns:
      - 192.168.1.201
    build:
      context: .
      dockerfile: Dockerfile-media
    network_mode: host
    expose:
      -  3678
    env_file: ./media.env
    environment:
      - TZ=Europe/London
      - PISTEREO_ALSA_DEVICE=equal
      - PISTEREO_LIBRESPOT_ALSA_MIXER_DEVICE=default
      - PISTEREO_LIBRESPOT_ALSA_MIXER_CONTROL=Master
      - PISTEREO_LIBRESPOT_PLAYBACK_BITRATE=160
      - PISTEREO_CLIENTID=""
      - PISTEREO_CLIENTSECRET=""
      - PISTEREO_BASEURL="http://192.168.1.201:3000"
      - PISTEREO_REMOTEDEVICE="Your Stereo"
      - PISTEREO_LOCALDEVICE="Your Device"
      - PISTEREO_LISTEN_PORT=3000
    container_name: pistereo2-media
    hostname: pistereo2-media
    restart: unless-stopped
    volumes:
      - /home/jcrocker/src/pistereo-config:/config
    devices:
      - /dev/snd:/dev/snd:rw
    privileged: true
