# Base container
FROM node:bullseye-slim AS base
ARG DEBIAN_FRONTEND=noninteractive
ENV NODE_ENV=production
ARG TARGETARCH
ENV TZ=UTC

RUN <<EOF
 apt update > /dev/null
 apt install -y tzdata ca-certificates > /dev/null
 apt install -y --no-install-recommends curl bash golang alsa-utils alsa-tools \
    libasound2 jq sudo libogg-dev libvorbis-dev libasound2-dev libasound2-plugin-equal libasound2-plugins \
    acl procps nano mpv socat gettext > /dev/null
 apt install -y glibc-source libsodium23 libsodium-dev build-essential libssl-dev libgdbm-dev libdb-dev libexpat-dev libncurses5-dev \                           libbz2-dev zlib1g-dev gawk bison > /dev/null
 apt clean -y > /dev/null
 rm -rf /var/cache/apt/archives /var/lib/apt/lists

 ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
 echo $TZ > /etc/timezone

 npm i -g @nestjs/cli grunt-cli pm2 dotenv-cli --no-audit
 npm cache clean --force
 pm2 install pm2-logrotate
 pm2 set pm2-logrotate:retain 2
 pm2 set pm2-logrotate:max_size 5M
EOF

# Build container
FROM base AS build
ARG TARGETARCH
WORKDIR /src
RUN mkdir -p build

COPY . .
RUN chmod +x ./buildscripts/*.sh
RUN npm i --no-audit --progress=false && cd server && NODE_ENV=development npm i --no-audit --progress=false && cd ../client && NODE_ENV=development npm i --no-audit --progress=false
ENV NODE_ENV=production
RUN grunt build-all
COPY ./buildscripts/startcontainer.sh ./build/startcontainer.sh
COPY ./buildscripts/start.sh ./build/server/start.sh
RUN chmod +x ./build/*.sh ./build/server/*.sh

# Runtime container
FROM base AS production
ENV NODE_ENV=production
ENV TZ=UTC
RUN npm config set fund false

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
RUN echo $TZ > /etc/timezone
RUN mkdir -p /config

WORKDIR /app
COPY --from=build /src/build .
COPY --from=build /src/config /config
COPY --from=build /src/mediaserver/audio/100-equal.conf /etc/alsa/conf.d/100-equal.conf
COPY --from=build /src/mediaserver/audio/asound.conf /etc/asound.conf

ENV PISTEREO_ALSA_DEVICE=equal
ENV PISTEREO_LIBRESPOT_ALSA_MIXER_DEVICE=
ENV PISTEREO_LIBRESPOT_ALSA_MIXER_CONTROL=Master
ENV PISTEREO_LIBRESPOT_PLAYBACK_BITRATE=160
ENV PISTEREO_CLIENTID=""
ENV PISTEREO_CLIENTSECRET=""
ENV PISTEREO_BASEURL=""
ENV PISTEREO_REMOTEDEVICE="Your Stereo"
ENV PISTEREO_LOCALDEVICE="Your Device"
ENV PISTEREO_DEVICEID=""
ENV PISTEREO_LISTEN_PORT=3000
ENV PISTEREO_MONGO_URL=""
ENV PISTEREO_MONGO_DB=pistereo2
ENV PISTEREO_MPV_SOCKET=/app/mediaserver/mpv/socket
ENV PISTEREO_STREAM_BUFFER_SIZE=1MiB
ENV PISTEREO_CACHE=/config/cache
ENV PISTEREO_CONFIG=/config
ENV PISTEREO_SPOTIFY_USERNAME=
ENV PISTEREO_SPOTIFY_ACCESS_TOKEN=
ENV IN_DOCKER="yes"
ENV PISTEREO_LIBRESPOT_MODE="zeroconf"

VOLUME /config
ENTRYPOINT [ "/bin/bash", "-E", "-c" ]
CMD ["/app/startcontainer.sh"]

