name: pistereo2

services:
  pistereo2:
    image: guidcruncher/pistereo2:latest
    depends_on:
      - pistereo2-mongodb
      - pistereo2-mediaserver
    extra_hosts:
      - pistereo2:127.0.0.1
    dns:
      - 192.168.1.201
    networks:
      pistereo2:
    expose:
      -  3000
    environment:
      - TZ=Europe/London
      - PISTEREO_CLIENTID="bfeb3abe6fa24e47803a2d7d72a4ee4c"
      - PISTEREO_CLIENTSECRET="91cfa30ef3334cb09bd6c0b2417c9c1c"
      - PISTEREO_BASEURL="https://music.pi.home"
      - PISTEREO_REMOTEDEVICE="Your Stereo"
      - PISTEREO_LOCALDEVICE="Your Device"
      - PISTEREO_LISTEN_PORT=3000
      - PISTEREO_MONGO_URL="mongodb://root:password@pistereo2-mongodb:27017/"
      - PISTEREO_MONGO_DB=pistereo2
      - PISTEREO_CACHE=/config/cache
    container_name: pistereo2
    hostname: pistereo2
    restart: unless-stopped
    volumes:
      - ./config:/config
    devices:
      - /dev/snd:/dev/snd:rw
    privileged: true

  pistereo2-mediaserver:
    image: guidcruncher/pistereo2:mediaserver
    extra_hosts:
      - pistereo2:127.0.0.1
    dns:
      - 192.168.1.201
    network_mode: host
    expose:
      -  3678
    environment:
      - TZ=Europe/London
      - PISTEREO_ALSA_DEVICE=equal
      - PISTEREO_LIBRESPOT_ALSA_MIXER_DEVICE=equal
      - PISTEREO_LIBRESPOT_ALSA_MIXER_CONTROL=Master
      - PISTEREO_LIBRESPOT_PLAYBACK_BITRATE=160
      - PISTEREO_CLIENTID="bfeb3abe6fa24e47803a2d7d72a4ee4c"
      - PISTEREO_CLIENTSECRET="91cfa30ef3334cb09bd6c0b2417c9c1c"
      - PISTEREO_REMOTEDEVICE="Your Stereo"
      - PISTEREO_LOCALDEVICE="Your Device"
      - PISTEREO_DEVICEID=""
      - PISTEREO_LISTEN_PORT=3001
      - PISTEREO_STREAM_BUFFER_SIZE=1MiB
      - PISTEREO_SPOTIFY_USERNAME=
      - PISTEREO_SPOTIFY_ACCESS_TOKEN=
      - PISTEREO_LIBRESPOT_MODE="zeroconf"
    container_name: pistereo2-mediaserver
    hostname: pistereo2-mediaserver
    restart: unless-stopped
    volumes:
      - ./config:/config
    devices:
      - /dev/snd:/dev/snd:rw
    privileged: true

  pistereo2-mongodb:
    image: mongo:4.4.18
    restart: unless-stopped
    container_name: pistereo2-mongodb
    hostname: pistereo2-mongodb
    networks:
      pistereo2:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/db:/data/db
      - ./configdb:/data/configdb
    ports:
      - 27017:27017

  pistereo2-mongo-express:
    image: mongo-express
    depends_on:
      - pistereo2-mongodb
    restart: unless-stopped
    hostname: pistereo2-mongo-express
    container_name: pistereo2-mongo-express
    networks:
      pistereo2:
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@pistereo2-mongodb:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  pistereo2:
    external: true
