# Base container
FROM --platform=linux/arm64 node:22-alpine AS base
ARG TARGETARCH
ENV NODE_ENV=production
ENV TZ=UTC

RUN npm config set fund false
RUN apk -U --no-cache add libpulse avahi libgcc gcompat alsa-lib envsubst mpv alsa-tools alsa-utils alsa-plugins alsaconf socat bash nano tzdata curl jq
COPY ./mediaserver/lib/caps.so /usr/lib
COPY ./mediaserver/lib/libasound* /usr/lib/alsa-lib/

RUN npm i -g @nestjs/cli grunt-cli pm2 dotenv-cli --no-audit
RUN npm cache clean --force
RUN pm2 install pm2-logrotate
RUN pm2 set pm2-logrotate:retain 2
RUN pm2 set pm2-logrotate:max_size 5M

# Build container
FROM base AS build
ARG TARGETARCH
WORKDIR /src
RUN mkdir -p build

COPY . .
RUN chmod +x ./buildscripts/*.sh
RUN npm i --no-audit --progress=false && cd server && NODE_ENV=development npm i --no-audit --progress=false && cd ../client && NODE_ENV=development npm i --no-audit --progress=false
ENV NODE_ENV=production
RUN grunt build-all
COPY ./buildscripts/startcontainer.sh ./build/startcontainer.sh
COPY ./buildscripts/start.sh ./build/server/start.sh
RUN chmod +x ./build/*.sh ./build/server/*.sh

# Runtime container
FROM base AS production
ENV NODE_ENV=production
ENV TZ=UTC
RUN npm config set fund false

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
RUN echo $TZ > /etc/timezone
RUN mkdir -p /config /streams /streams-base

WORKDIR /app
COPY --from=build /src/build .
COPY --from=build /src/config /config
COPY --from=build /src/mediaserver/audio/100-equal.conf /etc/alsa/conf.d/100-equal.conf
COPY --from=build /src/mediaserver/audio/asound.conf /etc/asound.conf
COPY ./userstream/* /streams-base

ENV PISTEREO_ALSA_DEVICE=equal
ENV PISTEREO_LIBRESPOT_ALSA_MIXER_DEVICE=
ENV PISTEREO_LIBRESPOT_ALSA_MIXER_CONTROL=Master
ENV PISTEREO_LIBRESPOT_PLAYBACK_BITRATE=160
ENV PISTEREO_CLIENTID=""
ENV PISTEREO_CLIENTSECRET=""
ENV PISTEREO_BASEURL=""
ENV PISTEREO_REMOTEDEVICE="Your Stereo"
ENV PISTEREO_LOCALDEVICE="Your Device"
ENV PISTEREO_DEVICEID=""
ENV PISTEREO_LISTEN_PORT=3000
ENV PISTEREO_MONGO_URL=""
ENV PISTEREO_MONGO_DB=pistereo2
ENV PISTEREO_MPV_SOCKET=/app/mediaserver/mpv/socket
ENV PISTEREO_STREAM_BUFFER_SIZE=1MiB
ENV PISTEREO_CACHE=/config/cache
ENV PISTEREO_CONFIG=/config
ENV PISTEREO_SPOTIFY_USERNAME=
ENV PISTEREO_SPOTIFY_ACCESS_TOKEN=
ENV IN_DOCKER="yes"
ENV PISTEREO_LIBRESPOT_MODE="zeroconf"
ENV PISTEREO_EQ_RESET=60

VOLUME /config
VOLUME /streams
ENTRYPOINT [ "/bin/bash", "-E", "-c" ]
CMD ["/app/startcontainer.sh"]

